import Router from "next/router";

const barList ={
    navigate: [
        {
            id: 1,
            name: "Giới thiệu",
            icon: "UserCircle",
            url: "/about",
          },
          {
            id: 2,
            name: "Dự án",
            icon: "Draft",
            url: "/project",
          },
          {
            id: 3,
            name: "Thư viện",
            icon: "Bulk",
            url: "/library",
          },
          {
            id: 4,
            name: "Ảnh chụp",
            icon: "History",
            url: "/photo",
          },
          {
            id: 5,
            name: "Viết linh tinh",
            icon: "EditSolid",
            url: "/writing",
          },
    ],
    social: [
        {
            id: 1,
            name: "Facebook",
            icon: "Facebook",
            link: "https://www.facebook.com/yun.khngn",
          },
          {
            id: 2,
            name: "Instagram",
            icon: "Instagram",
            link: "https://instagram.com/yun.khngn",
          },
          {
            id: 3,
            name: "Github",
            icon: "Github",
            link: "https://github.com/yunkhngn",
          },
          {
            id: 4,
            name: "Behance",
            icon: "Behance",
            link: "https://www.behance.net/yunkhngn_",
          },
    ],
    actions: [
      {
        id: "homeAction",
        name: "Trang chủ",
        shortcut: ["t"],
        keywords: "back home, trang chu",
        section: "Navigation",
        perform: () => Router.push('/'),
        subtitle: "Về lại trang chủ.",
      },
      {
        id: "aboutMeAction",
        name: "Giới thiệu",
        shortcut: ["g"],
        keywords: "gioi thieu ve toi",
        section: "Navigation",
        perform: () => Router.push('/about'),
        subtitle: "Giới thiệu về tớ.",
      },
      {
        id: "projectsAction",
        name: "Dự án",
        shortcut: ["d"],
        keywords: "project projects du an work featured",
        section: "Navigation",
        perform: () => Router.push('/project'),
        subtitle: "Các dự án của tớ.",
      },
      {
        id: "libraryAction",
        name: "Thư viện",
        shortcut: ["l"],
        keywords: "library thu vien design work behance",
        section: "Navigation",
        perform: () => Router.push('/library'),
        subtitle: "Thư viện dự án thiết kế.",
      },
      {
        id: "photoAction",
        name: "Ảnh chụp",
        shortcut: ["p"],
        keywords: "library thu vien anh chup photo",
        section: "Navigation",
        perform: () => Router.push('/photo'),
        subtitle: "Ảnh tớ chụp.",
      },
      {
        id: "writingsAction",
        name: "Viết linh tinh",
        shortcut: ["v"],
        keywords: "writing writings viet linh tinh blog",
        section: "Navigation",
        perform: () => Router.push('/writing'),
        subtitle: "Chỗ tớ viết linh tinh.",
      },
      {
        id: "scrollToTopAction",
        name: "Kéo lên",
        shortcut: ["s","t"],
        keywords: "scroll top",
        section: "Preferences",
        perform: () => window.scrollTo(0, 0),
        subtitle: "Kéo lên trên cùng.",
      },
      {
        id: "scrollToBotAction",
        name: "Kéo xuống dưới",
        shortcut: ["s","b"],
        keywords: "scroll bottom",
        section: "Preferences",
        perform: () => window.scrollTo(0, document.body.scrollHeight),
        subtitle: "Kéo xuống dưới cùng.",
      },
      {
        id: "facebookAction",
        name: "Facebook",
        shortcut: ["f","b"],
        keywords: "facebook social media",
        section: "Social media",
        perform: () => window.open('https://www.facebook.com/yun.khngn/', '_blank'),
        subtitle: "Facebook của tớ.",
      },
      {
        id: "instagramAction",
        name: "Instagram",
        shortcut: ["i","g"],
        keywords: "instagram social media",
        section: "Social media",
        perform: () => window.open('https://www.instagram.com/yun.khngn', '_blank'),
        subtitle: "Instagram của tớ.",
      },
      {
        id: "githubAction",
        name: "Github",
        shortcut: ["g","h"],
        keywords: "github social media",
        section: "Social media",
        perform: () => window.open('https://github.com/yunkhngn', '_blank'),
        subtitle: "Github có đăng các dự án của tớ.",
      },
      {
        id: "behanceAction",
        name: "Behance",
        shortcut: ["b","e"],
        keywords: "behance social media",
        section: "Social media",
        perform: () => window.open('https://www.behance.net/yunkhngn_', '_blank'),
        subtitle: "Các dự án thiết kế của tớ trên Behance.",
      },
    ]
}

export default barList