export {default as Template} from './Template';
export {default as Title} from './Title';
export {default as Para} from './Paragraph';
export {default as AnimatedTags} from './AnimatedTags';
export {default as Metatags} from './Metatags';
export {default as ThemeLoader} from './ThemeLoader';
export {default as Noti} from './Noti';
export {default as ElementSpace} from './ElementSpace';
export {default as WarnBeforeUnload} from './WarnBeforeUnload';
export {default as SocialLink} from './SocialLink/SocialLink'
export {default as Spacer} from './Spacer'
export {default as Snake} from './Snake'
export {default as ImagePreview} from './ImagePreview'
export {default as Footer} from './Footer'
export {default as ModalAsk} from './ModalAsk'
export {default as Search} from './Search'
export {default as RowContent} from './RowContent'
export {default as Back} from './Back'