import Router from "next/router";

const barList ={
    navigate: [
        {
            id: 1,
            name: "About",
            icon: "UserCircle",
            url: "/about",
          },
          {
            id: 2,
            name: "Project",
            icon: "Draft",
            url: "/project",
          },
          {
            id: 3,
            name: "Photo",
            icon: "Bulk",
            url: "/photo",
          },
          {
            id: 4,
            name: "Writing",
            icon: "EditSolid",
            url: "/writing",
          },
    ],
    social: [
        {
            id: 1,
            name: "Facebook",
            icon: "Facebook",
            link: "https://www.facebook.com/yun.khngn",
          },
          {
            id: 2,
            name: "Instagram",
            icon: "Instagram",
            link: "https://instagram.com/yun.khngn",
          },
          {
            id: 3,
            name: "Github",
            icon: "Github",
            link: "https://github.com/yunkhngn",
          },
          {
            id: 4,
            name: "Behance",
            icon: "Behance",
            link: "https://www.behance.net/yunkhngn_",
          },
    ],
    actions: [
      {
        id: "homeAction",
        name: "Trang chủ",
        shortcut: ["1"],
        keywords: "back home, trang chu",
        section: "Navigation",
        perform: () => Router.push('/'),
        subtitle: "Về lại trang chủ.",
      },
      {
        id: "aboutMeAction",
        name: "Giới thiệu",
        shortcut: ["2"],
        keywords: "gioi thieu ve toi",
        section: "Navigation",
        perform: () => Router.push('/about'),
        subtitle: "Giới thiệu về tớ.",
      },
      {
        id: "projectsAction",
        name: "Dự án",
        shortcut: ["3"],
        keywords: "project projects du an work featured",
        section: "Navigation",
        perform: () => Router.push('/project'),
        subtitle: "Các dự án của tớ.",
      },
      {
        id: "photoAction",
        name: "Ảnh chụp",
        shortcut: ["4"],
        keywords: "library thu vien anh chup photo",
        section: "Navigation",
        perform: () => Router.push('/photo'),
        subtitle: "Ảnh tớ chụp.",
      },
      {
        id: "writingsAction",
        name: "Viết linh tinh",
        shortcut: ["5"],
        keywords: "writing writings viet linh tinh blog",
        section: "Navigation",
        perform: () => Router.push('/writing'),
        subtitle: "Chỗ tớ viết linh tinh.",
      },
      {
        id: "scrollToTopAction",
        name: "Kéo lên",
        shortcut: ["w"],
        keywords: "scroll top",
        section: "Preferences",
        perform: () => window.scrollBy({ top: -window.innerHeight / 2, behavior: 'smooth' }),
        subtitle: "Kéo lên trên.",
      },
      {
        id: "scrollToBotAction",
        name: "Kéo xuống dưới",
        shortcut: ["s"],
        keywords: "scroll bottom",
        section: "Preferences",
        perform: () => window.scrollBy({ top: window.innerHeight / 2, behavior: 'smooth' }),
        subtitle: "Kéo xuống dưới cùng.",
      },
      {
        id: "backAction",
        name: "Quay lại",
        shortcut: ["a"],
        keywords: "back to previous page",
        section: "Preferences",
        perform: () => Router.back(),
        subtitle: "Quay lại.",
      },
      {
        id: "nextAction",
        name: "Trang tiếp",
        shortcut: ["d"],
        keywords: "back to previous page",
        section: "Preferences",
        perform: () => window.history.forward(),
        subtitle: "Quay lại.",
      },
      {
        id: "facebookAction",
        name: "Facebook",
        shortcut: ["f","b"],
        keywords: "facebook social media",
        section: "Social media",
        perform: () => window.open('https://www.facebook.com/yun.khngn/', '_blank'),
        subtitle: "Facebook của tớ.",
      },
      {
        id: "instagramAction",
        name: "Instagram",
        shortcut: ["i","g"],
        keywords: "instagram social media",
        section: "Social media",
        perform: () => window.open('https://www.instagram.com/yun.khngn', '_blank'),
        subtitle: "Instagram của tớ.",
      },
      {
        id: "githubAction",
        name: "Github",
        shortcut: ["g","h"],
        keywords: "github social media",
        section: "Social media",
        perform: () => window.open('https://github.com/yunkhngn', '_blank'),
        subtitle: "Github có đăng các dự án của tớ.",
      },
      {
        id: "behanceAction",
        name: "Behance",
        shortcut: ["b","e"],
        keywords: "behance social media",
        section: "Social media",
        perform: () => window.open('https://www.behance.net/yunkhngn_', '_blank'),
        subtitle: "Các dự án thiết kế của tớ trên Behance.",
      },
      {
        id: "contactAction",
        name: "Liên hệ",
        shortcut: ["7"],
        keywords: "contact lien he email",
        section: "Navigation",
        perform: () => Router.push('/contact'),
        subtitle: "Liên hệ với tớ.",
      },
    ]
}

export default barList